module.exports = {
  name: '                    Alex Dodd',
  email: 'hello@alexdodd.ca',
  handle: 'helloalexdodd',
  title: 'Full Stack Developer',
  twitter: 'https://twitter.com/',
  gitHub: 'https://github.com/',
  linkedIn: 'https://linkedin.com/in/',
  website: 'https://alexdodd.ca',
  repo: 'https://github.com/helloalexdodd/npx-helloalexdodd',
  npm: 'npx alexdodd',
  npmLink: 'https://www.npmjs.com/~alexdodd',

  labelTitle: '       Title:',
  labelTwitter: '    Twitter:',
  labelGitHub: '     GitHub:',
  labelLinkedIn: '   LinkedIn:',
  labelWeb: '        Web:',
  labelNpm: '        NPX:',
};
